#!/usr/bin/env python3
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, HRFlowable
import os
TWIST = HexColor("#FF6B2B")
OAK = HexColor("#1A1A1E")
CREAM = HexColor("#FFF8EC")
GOLD = HexColor("#F2B705")
JAL = HexColor("#2E7D32")
GREY = HexColor("#8A8D93")
ROOT = os.path.dirname(os.path.dirname(__file__))
IMG_DIR = os.path.join(ROOT, "public/img")
OUT = os.path.join(os.path.dirname(__file__), "TWIST805_DoorDash_Menu.pdf")
def img_exists(name):
    if not name: return None
    p=os.path.join(IMG_DIR,name)
    return p if os.path.isfile(p) else None
styles=getSampleStyleSheet()
sTitle=ParagraphStyle('title',parent=styles['Heading1'],fontName='Helvetica-Bold',fontSize=30,leading=30,textColor=TWIST,alignment=TA_CENTER)
sTag=ParagraphStyle('tag',parent=styles['Normal'],fontName='Helvetica',fontSize=6.5,leading=8,textColor=white,alignment=TA_CENTER)
sH2=ParagraphStyle('h2',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=9,leading=11,textColor=TWIST,spaceBefore=6,spaceAfter=3)
sSmall=ParagraphStyle('small',parent=styles['Normal'],fontName='Helvetica',fontSize=6,leading=7,textColor=HexColor("#444444"))
sPrice=ParagraphStyle('price',parent=styles['Normal'],fontName='Helvetica-Bold',fontSize=7,leading=9,textColor=OAK,alignment=TA_CENTER)
def header(c,doc):
    c.saveState()
    c.setFillColor(OAK)
    c.rect(0,doc.pagesize[1]-72,doc.pagesize[0],72,stroke=0,fill=1)
    c.setFillColor(TWIST)
    c.rect(0,doc.pagesize[1]-72-5,doc.pagesize[0],5,stroke=0,fill=1)
    c.restoreState()
def footer(c,doc):
    c.saveState()
    c.setFillColor(OAK)
    c.rect(0,0,doc.pagesize[0],34,stroke=0,fill=1)
    c.setFillColor(HexColor("#B0B0B0"))
    c.setFont("Helvetica",5.2)
    c.drawCentredString(doc.pagesize[0]/2,21,"TWIST 805  |  Braided Stuffed Crust  |  Paso Robles 93446 + SLO 805  |  Ghost Kitchen  |  Prices include braided upsell")
    c.setFont("Helvetica",4.5)
    c.drawCentredString(doc.pagesize[0]/2,11,"Images 2048x1152 16:9  |  No text/logos on food  |  Centered 60% fill  |  Own rights  |  13\" / 18\" XL / 24\" Giant")
    c.restoreState()
doc=SimpleDocTemplate(OUT,pagesize=LETTER,leftMargin=0.35*inch,rightMargin=0.35*inch,topMargin=0.88*inch,bottomMargin=0.48*inch,title="TWIST 805 DoorDash Menu")
story=[]
story.append(Spacer(1,0.02*inch))
story.append(Paragraph('<font color="#FF6B2B"><b>TWIST</b></font> <font color="white"><b>805</b></font>', ParagraphStyle('h',parent=sTitle,textColor=white,alignment=TA_CENTER,fontSize=36)))
story.append(Paragraph('<font color="#F2B705">BRAIDED STUFFED CRUST</font><font color="white">  ·  Giant Flavor  ·  Paso Robles & SLO</font>', sTag))
story.append(Paragraph('<font color="white" size="6">Ghost Kitchen  ·  (805) 439-2383  ·  Daily 11AM–10PM  ·  Braided Stuffed Crust +$3.99 / $5.99 / $7.99</font>', ParagraphStyle('sub',parent=sTag,fontSize=6)))
story.append(Spacer(1,0.09*inch))
notice=Paragraph('<b>DoorDash-first  ·  16:9 photos  ·  No logos  ·  One item per photo  ·  Braided stuffed crust is the hero</b> &nbsp; <font color="#FF6B2B"><b>805</b></font>', ParagraphStyle('notice',parent=styles['Normal'],fontName='Helvetica-Bold',fontSize=6,leading=8,textColor=white,alignment=TA_CENTER))
t=Table([[notice]],colWidths=[7.5*inch],style=TableStyle([('BACKGROUND',(0,0),(-1,-1),TWIST),('ROUNDEDCORNERS',[4,4,4,4]),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]))
story.append(t)
story.append(Spacer(1,0.08*inch))
def pizza_row(img,name,desc,prices,badge=None):
    p=img_exists(img)
    im=Image(p,width=0.58*inch,height=0.44*inch) if p else Paragraph('',sSmall)
    badge_html=f' <font color="#FF6B2B" size="5"><b>{badge}</b></font>' if badge else ''
    inner=Table([[im, Paragraph(f"<b>{name}</b>{badge_html}<br/><font size='5' color='#555555'>{desc}</font>", ParagraphStyle('in',parent=sSmall,leftIndent=3,fontSize=6))]],colWidths=[0.64*inch,2.22*inch])
    inner.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'TOP')]))
    price_para=Paragraph(f"<b>{prices[0]}</b> <font size='5' color='#8A8D93'>13\"</font>  |  <b>{prices[1]}</b> <font size='5' color='#8A8D93'>18\"XL</font>  |  <font color='#FF6B2B'><b>{prices[2]}</b></font> <font size='5' color='#8A8D93'>24\"Gi</font>" if len(prices)==3 else f"<b>{prices[0]}</b> 13\"  |  <b>{prices[1]}</b> 18\"XL", ParagraphStyle('pr',parent=sPrice,fontSize=6.5,alignment=TA_CENTER))
    row=Table([[inner, price_para]],colWidths=[2.90*inch,1.35*inch])
    row.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('BOTTOMPADDING',(0,0),(-1,-1),3),('TOPPADDING',(0,0),(-1,-1),2)]))
    return row
def simple_row(img,name,desc,price,badge=None):
    p=img_exists(img)
    im=Image(p,width=0.52*inch,height=0.40*inch) if p else Paragraph('',sSmall)
    badge_html=f' <font color="#FF6B2B" size="5"><b>{badge}</b></font>' if badge else ''
    inner=Table([[im, Paragraph(f"<b>{name}</b>{badge_html}<br/><font size='5' color='#555555'>{desc}</font>", ParagraphStyle('in2',parent=sSmall,leftIndent=3,fontSize=6))]],colWidths=[0.58*inch,2.28*inch])
    inner.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'TOP')]))
    price_para=Paragraph(f"<b>{price}</b>", sPrice)
    row=Table([[inner, price_para]],colWidths=[2.90*inch,0.85*inch])
    row.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('BOTTOMPADDING',(0,0),(-1,-1),3)]))
    return row

story.append(Paragraph("BRAIDED SIGNATURES — Stuffed Twist Crust", sH2))
story.append(HRFlowable(width="100%",thickness=1,color=TWIST,spaceBefore=1,spaceAfter=3))
story.append(pizza_row("pizza-corn-jalapeno-braid.jpg","Paso Corn Twist","Sweet corn + jalapeño + mozzarella, braided & parmesan-dusted.",["18.95","27.95","38.95"],"★ NEW Signature"))
story.append(pizza_row("pizza-feta-basil-braid.jpg","Feta & Basil Twist","Feta, sausage, spinach, zucchini, red onion, fresh basil.",["19.95","28.95","39.95"],"CHEF'S"))
story.append(pizza_row("pizza-house-combo-braid.jpg","House Combo Braid","Artichoke, tomato, red onion, sausage, mushrooms. Loaded.",["18.95","27.95","38.95"],"Popular"))
story.append(pizza_row("pizza-meat-braid.jpg","Meat Lovers Braid","Pepperoni + ground beef — double meat blanket.",["19.95","28.95","39.95"],None))
story.append(pizza_row("pizza-supreme-braid.jpg","Supreme 805","Pepperoni, salami, ham, black olives, mushrooms, onion, pepperoncini.",["20.95","29.95","41.95"],"Supreme"))
story.append(pizza_row("pizza-spicy-braid.jpg","Spicy SLO Braid","Pepperoni, sausage, jalapeño, olives, mushrooms, onion.",["19.95","28.95","39.95"],"Spicy"))
story.append(pizza_row("pizza-pepperoni-xl-braid.jpg","Pepperoni Overload XL","60+ cup pepperoni edge-to-edge, extra cheese.",["18.95","27.95","38.95"],"Popular"))
story.append(pizza_row("pizza-heart-cheese.jpg","Heart Cheese Twist (Limited)","Heart-shaped, braided edge, extra mozzarella.",["17.95","26.95","—"],"Limited"))
story.append(Spacer(1,0.06*inch))
# BYO
byo=Paragraph("<b>BUILD YOUR OWN — Braided Choice</b><br/><font size='5' color='#555555'>Base Cheese 13\" $14.95 / 18\" $21.95 / 24\" $32.95 — then choose crust & toppings. Max 5 toppings.</font>", sSmall)
t=Table([[byo]],colWidths=[7.5*inch])
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),CREAM),('BOX',(0,0),(-1,-1),0.5,HexColor("#E8D9B8")),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5),('LEFTPADDING',(0,0),(-1,-1),6)]))
story.append(t)
story.append(Spacer(1,0.03*inch))
mods=Paragraph("<b>MODIFIERS (DoorDash)</b> &nbsp; <b>Crust*:</b> Original / <b>Braided Stuffed +$3.99/$5.99/$7.99</b> / Thin &nbsp;|&nbsp; <b>Sauce:</b> Tomato / White +$1 / BBQ +$1 &nbsp;|&nbsp; <b>Cheese:</b> Light/Regular/Extra +$2.50<br/><b>Meats +$2.50/3.50/4.50:</b> Pepperoni, Sausage, Beef, Salami, Ham &nbsp;|&nbsp; <b>Veg +$1.75/2.75/3.50:</b> Corn, Jalapeño, Spinach, Zucchini, Onion, Tomato, Mushroom, Artichoke, Olives, Pepperoncini, Basil<br/><b>Premium +$2.75/3.75/4.50:</b> Feta, Blue Cheese &nbsp;|&nbsp; <b>Cut:</b> Triangle/Square &nbsp;|&nbsp; <b>Add Dip:</b> Ranch/Blue Cheese", ParagraphStyle('mods',parent=sSmall,fontSize=5.5,leading=7,textColor=HexColor("#444444")))
t2=Table([[mods]],colWidths=[7.5*inch])
t2.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),HexColor("#FFF8EC")),('BOX',(0,0),(-1,-1),0.5,HexColor("#E8D9B8")),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4),('LEFTPADDING',(0,0),(-1,-1),6)]))
story.append(t2)
story.append(Spacer(1,0.08*inch))
story.append(Paragraph("805 SIDES & MORE", sH2))
story.append(HRFlowable(width="100%",thickness=1,color=TWIST,spaceBefore=1,spaceAfter=3))
story.append(simple_row("mozzarella-sticks.jpg","Mozzarella Sticks (6)","Panko-crisp, house marinara.","9.95",None))
story.append(simple_row("buffalo-wings.jpg","Buffalo Wings (8)","Glossy buffalo, ranch & celery.","12.95","Popular"))
story.append(simple_row("garlic-bread.jpg","Braided Garlic Bread","Garlic butter, braided & cheese-dusted.","8.95",None))
story.append(simple_row("loaded-fries.jpg","Loaded Twist Fries","Cheddar, scallions, ranch, bacon.","9.95",None))
story.append(Paragraph("PASTA", sH2))
story.append(HRFlowable(width="100%",thickness=1,color=TWIST,spaceBefore=1,spaceAfter=3))
story.append(simple_row("pasta-lasagna.jpg","Spaghetti & Meatballs","Marinara, meatballs, garlic bread side.","13.95",None))
story.append(Paragraph("DOLCI", sH2))
story.append(HRFlowable(width="100%",thickness=1,color=TWIST,spaceBefore=1,spaceAfter=3))
story.append(simple_row("cheesecake.jpg","Cannoli","Cream-filled, chocolate drizzle.","5.95",None))
story.append(simple_row("lava-brownie.jpg","NY Cheesecake","Paso berry coulis.","7.95",None))
story.append(Paragraph("DRINKS — Generic (DoorDash safe)", sH2))
story.append(HRFlowable(width="100%",thickness=1,color=TWIST,spaceBefore=1,spaceAfter=3))
for n,p in [("House Mint Lemonade 16oz","4.95"),("Cola 330ml","2.95"),("Lemon-Lime 330ml","2.95"),("Sparkling Water 355ml","3.50"),("Cold Brew 16oz","4.95")]:
    img="mint-lemonade.jpg" if "Lemonade" in n else ""
    story.append(simple_row(img,n,"","%s"%p,None))
story.append(Paragraph("DIPS & SAUCES — $1.50 each · 3 for $3.95", sH2))
story.append(HRFlowable(width="100%",thickness=1,color=TWIST,spaceBefore=1,spaceAfter=3))
story.append(Paragraph("Ranch &nbsp;|&nbsp; Blue Cheese &nbsp;|&nbsp; Garlic Whip &nbsp;|&nbsp; Marinara &nbsp;|&nbsp; Hot Honey", ParagraphStyle('dips',parent=sSmall,alignment=TA_CENTER,fontSize=6.5)))
story.append(Spacer(1,0.08*inch))
combo=Paragraph('<b><font color="#F2B705" size="11">GIANT TWIST BUNDLE — 24\"</font></b><br/><font color="white" size="7">1 × 24\" Giant Braided + 2 Sides + 4 Drinks — Feeds 6-8</font><br/><font color="white" size="15"><b>89.95</b></font><br/><font color="#FF6B2B" size="6"><b>Save $22 — #1 Family Upsell</b></font>', ParagraphStyle('combo',parent=styles['Normal'],alignment=TA_CENTER,textColor=white,leading=11))
t=Table([[combo]],colWidths=[7.5*inch])
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),TWIST),('ROUNDEDCORNERS',[8,8,8,8]),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8)]))
story.append(t)
story.append(Spacer(1,0.06*inch))
ups=Paragraph("<b>UPSELL ENGINE</b> &nbsp; Braided? +$3.99 (45% add) &nbsp;|&nbsp; Add Dip +$1.50 &nbsp;|&nbsp; Giant Up 18→24 +$11 &nbsp;|&nbsp; Add Cannoli +$5.95", ParagraphStyle('ups',parent=sSmall,textColor=white,alignment=TA_CENTER,fontSize=6))
t=Table([[ups]],colWidths=[7.5*inch])
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),OAK),('ROUNDEDCORNERS',[6,6,6,6]),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]))
story.append(t)
story.append(Spacer(1,0.06*inch))
psy=Paragraph('<b>Psychology:</b> Braided +$3.99 = 80% margin hero · Giant anchor makes XL feel value · Corn Twist is Instagrammable differentiator vs all thin crust in 93446 · Heart limited drives urgency.', ParagraphStyle('psy',parent=sSmall,fontSize=5,leading=6,textColor=HexColor("#666666")))
t=Table([[psy]],colWidths=[7.5*inch])
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),HexColor("#FFF8EC")),('ROUNDEDCORNERS',[5,5,5,5]),('BOX',(0,0),(-1,-1),0.5,HexColor("#E8D9B8")),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4),('LEFTPADDING',(0,0),(-1,-1),6)]))
story.append(t)
doc.build(story,onFirstPage=lambda c,d:(header(c,d),footer(c,d)),onLaterPages=lambda c,d:(header(c,d),footer(c,d)))
print(f"PDF TWIST805 generated: {OUT} {os.path.getsize(OUT)} bytes")
